### ISSUE TITLE
Hacktoberfest checklist: prepare project for contributions by following best practices

### ISSUE THREAD

**Issue by DerekNonGeneric** [openinf/gh-file-importer#110]
- [x] Add the “hacktoberfest” topic to your repository to **opt-in to Hacktoberfest** and indicate you’re looking for contributions.

- [ ] Apply the “hacktoberfest” label to issues you want contributors to help within your GitHub or GitLab project.

- [ ] Add a `CONTRIBUTING.md` file with contribution guidelines to your repository.

- [ ] Choose issues that have a well-defined scope and are self-contained.

- [x] Adopt a code of conduct to create a greater sense of inclusion and community for contributors.

- [x] Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.

- [x] Reject any spammy requests you receive by labeling them as “spam”, and any other invalid contributions by closing them or labeling them as “invalid”.

Refs: https://hacktoberfest.com/participation/#maintainers
